#### 2024-12-27

In [2]:
import numpy as np
import pandas as pd

In [3]:
# score = int(input("점수 입력 : "))
score = 90

message = "success" if score >= 60 else "failure"
print(message)

success


In [4]:
squares = []
numbers = [1, 2, 3, 4, 5]
for x in numbers:
    squares.append(x**2)
print(squares)

[1, 4, 9, 16, 25]


In [5]:
# numbers = int(input("숫자 입력"))
numbers = [x for x in range(1, 6)]
squares = [x**2 for x in numbers]
print(squares)

[1, 4, 9, 16, 25]


In [6]:
num = [x for x in range(1, 7)]
even_num = [n for n in num if n%2==0]
print(even_num)

[2, 4, 6]


In [7]:
even = list(filter(lambda x: x%2==0, num))
print(even)

[2, 4, 6]


In [8]:
np.__version__

'2.2.1'

In [9]:
arr  = np.array([x for x in range(1, 11)])
arr.reshape(2, 5)

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10]])

In [10]:
arr  = np.array([x*2 for x in range(1, 11)])
print(arr)

[ 2  4  6  8 10 12 14 16 18 20]


In [11]:
data = [0, 1, 2, 3, 4, 5, 6, 7, 8, 9]
ans = np.array(data)
ans = ans*2
print(ans)

[ 0  2  4  6  8 10 12 14 16 18]


In [12]:
data = [0, 1, 2, 3, 4, 5, 6, 7, 8, 9]
ans = []
for di in data:
    ans.append(2*di)
ans

[0, 2, 4, 6, 8, 10, 12, 14, 16, 18]

In [13]:
a = np.array([[0, 1, 2], [3, 4, 5]])
print(a[0][0], a[0][1], a[1][2])

0 1 5


In [14]:
a = np.array([[0, 1, 2, 3], [4, 5, 6, 7]])
print(a[0])
print(a[:,1])
print(a[1][1:])
print(a[:, 0:2])

[0 1 2 3]
[1 5]
[5 6 7]
[[0 1]
 [4 5]]


In [15]:
a = np.array([1, 2, 3])
b = np.array([10, 20, 30])

print(a*2 + b)
print(a == 2)
print(b > 10)
print((a==2) & (b > 10))

[12 24 36]
[False  True False]
[False  True  True]
[False  True False]


In [16]:
a = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9])
print(a[a%2==0])

[2 4 6 8]


In [17]:
a = np.array([[1, 2, 3, 4], [5, 6, 7, 8], [9, 10, 11, 12]])
idx=np.array([2, 0, 1])
print(a[2, :], a[0], a[1])
a[idx]
a[:, [0,3]]
a[[2,0,1], :]

[ 9 10 11 12] [1 2 3 4] [5 6 7 8]


array([[ 9, 10, 11, 12],
       [ 1,  2,  3,  4],
       [ 5,  6,  7,  8]])

In [18]:
x = np.array([1, 2, 3,4, 5, 6, 7, 8, 9, 10,11, 12, 13, 14, 15, 16, 17, 18, 19, 20])
 
# 배열에서 3의 배수를 찾아주세요.
# 배열에서 4로 나누면 1이 남는 수를 찾아주세요.
# 배열에서 3으로 나누면 나누어지고 4로 나누면 1이 남는 수를 찾아주세요.
 
print(a[a%3==0])
print(a[a%4==1])
print(a[ (a%3==0) & (a%4==1) ])

[ 3  6  9 12]
[1 5 9]
[9]


In [19]:
s = pd.Series([3, -5, 7, 4], index=['a', 'b', 'c', 'd'])
print(s)
print(type(s))

a    3
b   -5
c    7
d    4
dtype: int64
<class 'pandas.core.series.Series'>


In [20]:
df = pd.DataFrame({'Division' : ['부산광역시', '전라남도', '강원도'], 
                   'Code' : ['051', '061', '033'],
                   'Population': [3354358, 1840921, 1535530]})

print(type(df))
df

<class 'pandas.core.frame.DataFrame'>


Division Code  Population
0    부산광역시  051     3354358
1     전라남도  061     1840921
2      강원도  033     1535530

In [21]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 3 entries, 0 to 2
Data columns (total 3 columns):
 #   Column      Non-Null Count  Dtype 
---  ------      --------------  ----- 
 0   Division    3 non-null      object
 1   Code        3 non-null      object
 2   Population  3 non-null      int64 
dtypes: int64(1), object(2)
memory usage: 204.0+ bytes


In [22]:
df = pd.read_csv('data\heroes.csv')
df

<>:1: SyntaxWarning: invalid escape sequence '\h'
<>:1: SyntaxWarning: invalid escape sequence '\h'
C:\Users\Public\Documents\ESTsoft\CreatorTemp\ipykernel_20556\1137886699.py:1: SyntaxWarning: invalid escape sequence '\h'
  df = pd.read_csv('data\heroes.csv')


이름  나이     직업     국적    키            재산
0   아이언맨  58    CEO     미국  174  1.150000e+10
1     토르  45      신  아스가르드  190           NaN
2  스파이더맨  18   고등학생     미국  177  6.000000e+02
3   원더우먼  27     공주  데미스키라  178           NaN
4     헐크  33  핵물리학자     미국  270  1.000000e+09
5   캡틴마블  25    파일럿     미국  170  3.400000e+08
6  블랙위도우  32    스파이    러시아  170  5.000000e+07

In [23]:
pd.options.display.float_format = '{:.0f}'.format

In [24]:
df

이름  나이     직업     국적    키          재산
0   아이언맨  58    CEO     미국  174 11500000000
1     토르  45      신  아스가르드  190         NaN
2  스파이더맨  18   고등학생     미국  177         600
3   원더우먼  27     공주  데미스키라  178         NaN
4     헐크  33  핵물리학자     미국  270  1000000000
5   캡틴마블  25    파일럿     미국  170   340000000
6  블랙위도우  32    스파이    러시아  170    50000000

In [25]:
df['국적']

0       미국
1    아스가르드
2       미국
3    데미스키라
4       미국
5       미국
6      러시아
Name: 국적, dtype: object

In [28]:
df['나이'].nlargest()

0    58
1    45
4    33
6    32
3    27
Name: 나이, dtype: int64

In [32]:
df.nlargest(3, '나이')

이름  나이     직업     국적    키          재산
0  아이언맨  58    CEO     미국  174 11500000000
1    토르  45      신  아스가르드  190         NaN
4    헐크  33  핵물리학자     미국  270  1000000000

In [38]:
df[0:2]

이름  나이   직업     국적    키          재산
0  아이언맨  58  CEO     미국  174 11500000000
1    토르  45    신  아스가르드  190         NaN

In [46]:
df.iloc[:, [0]]

이름
0   아이언맨
1     토르
2  스파이더맨
3   원더우먼
4     헐크
5   캡틴마블
6  블랙위도우

In [47]:
df['나이']

0    58
1    45
2    18
3    27
4    33
5    25
6    32
Name: 나이, dtype: int64

In [52]:
df.loc[0, '이름']

'아이언맨'

In [56]:
print(df.iloc[0])

이름          아이언맨
나이            58
직업           CEO
국적            미국
키            174
재산   11500000000
Name: 0, dtype: object


In [57]:
df2 = df.copy()
df2.iloc[5, 1 ] = None

df2

이름  나이     직업     국적    키          재산
0   아이언맨  58    CEO     미국  174 11500000000
1     토르  45      신  아스가르드  190         NaN
2  스파이더맨  18   고등학생     미국  177         600
3   원더우먼  27     공주  데미스키라  178         NaN
4     헐크  33  핵물리학자     미국  270  1000000000
5   캡틴마블 NaN    파일럿     미국  170   340000000
6  블랙위도우  32    스파이    러시아  170    50000000

In [59]:
df2.index = ['a', 'b', 'c', 'd', 'e', 'f', 'g']
df2

이름  나이     직업     국적    키          재산
a   아이언맨  58    CEO     미국  174 11500000000
b     토르  45      신  아스가르드  190         NaN
c  스파이더맨  18   고등학생     미국  177         600
d   원더우먼  27     공주  데미스키라  178         NaN
e     헐크  33  핵물리학자     미국  270  1000000000
f   캡틴마블 NaN    파일럿     미국  170   340000000
g  블랙위도우  32    스파이    러시아  170    50000000

In [60]:
df2.loc['a' : 'b', '이름' : '직업']

이름  나이   직업
a  아이언맨  58  CEO
b    토르  45    신

In [63]:
df2[df2['재산'].isnull()]

이름  나이  직업     국적    키  재산
b    토르  45   신  아스가르드  190 NaN
d  원더우먼  27  공주  데미스키라  178 NaN

In [69]:
df[  (df['나이'] > 30) & (df['나이'] < 50)  ]

이름  나이     직업     국적    키         재산
1     토르  45      신  아스가르드  190        NaN
4     헐크  33  핵물리학자     미국  270 1000000000
6  블랙위도우  32    스파이    러시아  170   50000000

In [82]:
df.loc[(df['나이'] > 30) & (df['나이'] < 50), '이름':'직업']

이름  나이     직업
1     토르  45      신
4     헐크  33  핵물리학자
6  블랙위도우  32    스파이

In [86]:
df2.rename(columns={'재산': "재산현황"}, inplace=True)
df2

이름  나이     직업     국적    키        재산현황
a   아이언맨  58    CEO     미국  174 11500000000
b     토르  45      신  아스가르드  190         NaN
c  스파이더맨  18   고등학생     미국  177         600
d   원더우먼  27     공주  데미스키라  178         NaN
e     헐크  33  핵물리학자     미국  270  1000000000
f   캡틴마블 NaN    파일럿     미국  170   340000000
g  블랙위도우  32    스파이    러시아  170    50000000